"""Export utilities for analysis results - JSON and CSV formats"""

import json
import csv
from io import StringIO
from typing import Dict, Any

def export_json(data: Dict[str, Any]) -> str:
    """Convert analysis result to JSON string for download.

    Args:
        data: Analysis result dict (basic_info, alerts, etc.)

    Returns:
        JSON string with Chinese characters preserved (ensure_ascii=False)
    """
    return json.dumps(data, ensure_ascii=False, indent=2)

def export_csv(data: Dict[str, Any]) -> str:
    """Convert analysis alerts to CSV format for download.

    Expected data structure:
        data['alerts'] = {
            'red': [{'feature': str, 'detail': str, 'meaning': str}],
            'yellow': [...],
            'green': [...],
            'score': int
        }

    Args:
        data: Analysis result with alerts

    Returns:
        CSV string with columns: 级别, 特征, 详情, 意义
    """
    output = StringIO()
    writer = csv.writer(output)

    # Header row
    writer.writerow(['级别', '特征', '详情', '意义'])

    alerts = data.get('alerts', {})

    # Red alerts
    for alert in alerts.get('red', []):
        if isinstance(alert, dict):
            writer.writerow([
                '红色',
                alert.get('feature', ''),
                alert.get('detail', ''),
                alert.get('meaning', '')
            ])

    # Yellow alerts
    for alert in alerts.get('yellow', []):
        if isinstance(alert, dict):
            writer.writerow([
                '黄色',
                alert.get('feature', ''),
                alert.get('detail', ''),
                alert.get('meaning', '')
            ])

    # Green alerts
    for alert in alerts.get('green', []):
        if isinstance(alert, dict):
            writer.writerow([
                '绿色',
                alert.get('feature', ''),
                alert.get('detail', ''),
                alert.get('meaning', '')
            ])

    # Add score row
    writer.writerow(['评分', '', '', f"{alerts.get('score', 0)}/100"])

    return output.getvalue()

def get_export_filename(address: str, format_type: str, analysis_type: str = 'analysis') -> str:
    """Generate filename for export download.

    Args:
        address: TRON address being analyzed
        format_type: "json" or "csv"
        analysis_type: Type of analysis ("analysis", "behavior", etc.)

    Returns:
        Filename like "tron_behavior_TUtP...NNw_20240115.json"
    """
    from datetime import datetime
    date_str = datetime.now().strftime('%Y%m%d')
    addr_short = address[:8] + address[-4:] if len(address) > 12 else address
    return f"tron_{analysis_type}_{addr_short}_{date_str}.{format_type}"

def get_pdf_filename(address: str, tool_type: str) -> str:
    """Generate filename for PDF export download.

    Args:
        address: Address being analyzed
        tool_type: Tool type identifier (e.g., 'tron_suspicious', 'eth_query')

    Returns:
        Filename like "tron_suspicious_TUtP...NNw_20240115.pdf"
    """
    from datetime import datetime
    date_str = datetime.now().strftime('%Y%m%d')
    # Sanitize address - use only alphanumeric chars
    addr_short = address[:8] + address[-4:] if len(address) > 12 else address
    return f"{tool_type}_{addr_short}_{date_str}.pdf"

def export_pdf(data: Dict[str, Any], tool_type: str) -> bytes:
    """Convert analysis result to PDF bytes for download.

    Args:
        data: Analysis result dict (basic_info, alerts, etc.)
        tool_type: Tool type identifier for title

    Returns:
        PDF bytes generated by WeasyPrint
    """
    from weasyprint import HTML

    # Build HTML content for PDF
    tool_names = {
        'tron_suspicious': 'TRON可疑特征分析',
        'tron_behavior': 'TRON地址行为分析',
        'eth_query': 'ETH交易查询',
        'uniswap': 'Uniswap追踪',
        'mixer': '混币器追踪',
        'btc': 'BTC交易分析',
        'cluster': '地址聚类',
        'cross_border': '跨境协查',
        'monitor': '多链监控',
        'obfuscation': '混淆攻击对抗',
        'asset_freeze': '资产追回冻结'
    }

    title = tool_names.get(tool_type, '链上分析报告')
    address = data.get('address', 'unknown')

    # Build HTML with inline CSS (PDF generation happens server-side)
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{ font-family: Arial, sans-serif; margin: 20px; color: #333; }}
            h1 {{ color: #1a1a1a; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }}
            h2 {{ color: #4a4a4a; margin-top: 20px; }}
            .info-grid {{ display: grid; grid-template-columns: 150px 1fr; gap: 8px; margin: 10px 0; }}
            .info-label {{ font-weight: bold; color: #666; }}
            .info-value {{ color: #333; }}
            .alert-section {{ margin: 15px 0; padding: 10px; border-radius: 5px; }}
            .alert-red {{ background-color: #fee2e2; border-left: 4px solid #ef4444; }}
            .alert-yellow {{ background-color: #fef3c7; border-left: 4px solid #f59e0b; }}
            .alert-green {{ background-color: #dcfce7; border-left: 4px solid #22c55e; }}
            .alert-item {{ margin: 5px 0; }}
            .score {{ font-size: 24px; font-weight: bold; margin: 20px 0; }}
            .footer {{ margin-top: 30px; font-size: 12px; color: #888; border-top: 1px solid #ddd; padding-top: 10px; }}
        </style>
    </head>
    <body>
        <h1>{title}</h1>
        <p><strong>分析地址:</strong> {address}</p>

        <h2>基本信息</h2>
        <div class="info-grid">
    """

    # Add basic info
    basic_info = data.get('basic_info', {})
    if basic_info:
        for key, value in basic_info.items():
            if isinstance(value, dict):
                continue  # Skip nested dicts
            html_content += f'<div class="info-label">{key}</div><div class="info-value">{value}</div>\n'
    else:
        html_content += '<div class="info-value">无基本信息</div>\n'

    html_content += """
        </div>

        <h2>风险提示</h2>
    """

    # Add alerts
    alerts = data.get('alerts', {})
    if alerts:
        score = alerts.get('score', 0)
        html_content += f'<div class="score">风险评分: {score}/100</div>\n'

        # Red alerts
        for alert in alerts.get('red', []):
            if isinstance(alert, dict):
                html_content += f"""
                <div class="alert-section alert-red">
                    <div class="alert-item"><strong>🔴 {alert.get('feature', '')}</strong></div>
                    <div class="alert-item">{alert.get('detail', '')}</div>
                    <div class="alert-item"><em>{alert.get('meaning', '')}</em></div>
                </div>
                """

        # Yellow alerts
        for alert in alerts.get('yellow', []):
            if isinstance(alert, dict):
                html_content += f"""
                <div class="alert-section alert-yellow">
                    <div class="alert-item"><strong>🟡 {alert.get('feature', '')}</strong></div>
                    <div class="alert-item">{alert.get('detail', '')}</div>
                    <div class="alert-item"><em>{alert.get('meaning', '')}</em></div>
                </div>
                """

        # Green alerts
        for alert in alerts.get('green', []):
            if isinstance(alert, dict):
                html_content += f"""
                <div class="alert-section alert-green">
                    <div class="alert-item"><strong>🟢 {alert.get('feature', '')}</strong></div>
                    <div class="alert-item">{alert.get('detail', '')}</div>
                    <div class="alert-item"><em>{alert.get('meaning', '')}</em></div>
                </div>
                """
    else:
        html_content += '<div class="info-value">无风险提示</div>\n'

    # Footer with disclaimer
    html_content += """
        <div class="footer">
            <p>⚠️ 本报告仅供参考，不作为法律证据使用。</p>
            <p>虚拟币犯罪调查工具集 (CIT) - 本地运行版</p>
        </div>
    </body>
    </html>
    """

    # Convert HTML to PDF
    pdf_bytes = HTML(string=html_content).write_pdf()
    return pdf_bytes